version: "3.3"
services:
  mysql_db:
    image: mysql:5.7.33
    container_name: db
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - host
volumes:
  mysql_db: {}
networks:
  host:
    driver: bridge
