server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        data:
          r2dbc: DEBUG
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile:
        - local
  application:
    name: WebFluxStudy
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  r2dbc:
    url: r2dbc:mysql://localhost:3308/fluxstudy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    pool:
      initial-size: 50
      max-size: 100
  data:
    r2dbc:
      repositories:
        enabled: true
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10000
    url: jdbc:mysql://localhost:3308/fluxstudy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true